CREATE TABLE  "COMPANIAS_TBL" 
   (	"ID_COMPANIA" NUMBER, 
	"NOMBRE_COMPANIA" VARCHAR2(240) NOT NULL ENABLE, 
	"ALIAS" VARCHAR2(200), 
	"DIRECCION" VARCHAR2(240), 
	"LOGO" BLOB, 
	"LOGO_CHARSET" VARCHAR2(255), 
	"LOGO_MIMETYPE" VARCHAR2(255), 
	"LOGO_NAME" VARCHAR2(255), 
	"COMPANIA_PADRE" NUMBER, 
	"TAGS" VARCHAR2(500), 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255), 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(255), 
	 PRIMARY KEY ("ID_COMPANIA")
  USING INDEX  ENABLE
   )
/

CREATE OR REPLACE EDITIONABLE TRIGGER  "COMPANIAS_TRG" 
  BEFORE INSERT ON COMPANIAS_TBL  
  FOR EACH ROW  
BEGIN  
   --evalua el id  
   IF :new.ID_COMPANIA IS NULL  
   THEN  
      :new.ID_COMPANIA := COMPANIAS_SEQ.NEXTVAL;  
   END IF;  
   
   -- columnas auditoria  
   --ESTANDAR-ORACLE
   :new.CREATION_DATE := SYSDATE;  
   :new.CREATED_BY := COALESCE(V('APP_USER'), SYS_CONTEXT ('USERENV', 'OS_USER'), USER);  
   :new.LAST_UPDATE_DATE := SYSDATE;  
   :new.LAST_UPDATED_BY := COALESCE(V('APP_USER'), SYS_CONTEXT ('USERENV', 'OS_USER'), USER);     
END COMPANIAS_TRG;
/
ALTER TRIGGER  "COMPANIAS_TRG" ENABLE
